export default {
  FETCH_SHOWS_REQUEST: 'FETCH_SHOWS_REQUEST',
  FETCH_SHOWS_SUCCESS: 'FETCH_SHOWS_SUCCESS',
  FETCH_SHOWS_ERROR: 'FETCH_SHOWS_ERROR',
  CHANGE_URL_PARAMS: 'CHANGE_URL_PARAMS',
  ADD_POSTER_URL: 'ADD_POSTER_URL',
};
