export default {
  ADD_SHOWS: 'ADD_SHOWS',
  GET_SHOWS_REQUEST: 'GET_SHOWS_REQUEST',
  GET_SHOWS_ERROR: 'GET_SHOWS_ERROR',
  RESET_SHOWS_FOR_PAGINATION: 'RESET_SHOWS_FOR_PAGINATION',
  RESET_FOR_NEW_FETCH: 'RESET_FOR_NEW_FETCH',
  GET_POSTERS_URL_SUCCESS: 'GET_POSTER_SUCCESS',
  GET_POSTER_URL_REQUEST: 'GET_POSTER_REQUEST',
  GET_POSTER_URL_ERROR: 'GET_POSTER_ERROR',
  GET_POSTER_URL_ADN_ID: 'GET_POSTER_URL_ADN_ID',
};
